### ISSUE TITLE
Solution files not detected if they are in a sub-directory i.e. src

### ISSUE THREAD

**Issue by BinToss** [yamachu/TargetFrameworksSwitcherForOmniSharp#3]
# Problem
`./*.sln` can be detected, but `./**/*.sln` is not. This shouldn't matter in the first place. See Solution.
For months, I thought the extension was just plain broken because the contents of its panel were always empty.

# Solution

Unless OmniSharp does not have a solution or project file selected, there should be no need to search for them.
Because OmniSharp "loads" a selected solution or project and its dependencies, TargetFrameworkSwitcher should instead try getting the selection (if not null?) from OmniSharp itself.

**Comment by yamachu** [comment]
Thanks for using this extension and reporting Issue!
I didn't notice because I had the solution directory open in vscode...

I tried to solve the above problem by recursively searching the directory.
It may slow down the initial load slightly, but could you please give it a try new version (v1.1.0)?

**Comment by BinToss** [comment]
![image](https://github.com/yamachu/TargetFrameworksSwitcherForOmniSharp/assets/7243190/84897443-c05b-4037-8baf-556b5e2eede5)
Seems to be working now. Excellent!

**Comment by yamachu** [comment]
Thanks for verifying 👍
